---
- hosts: backend
  become: yes

  tasks:
    - name: Install required packages
      apt:
        name:
          - curl
          - wget
        state: present
        update_cache: yes

    - name: Download Netdata installation script
      get_url:
        url: https://my-netdata.io/kickstart.sh
        dest: /tmp/netdata-install.sh
        mode: '0755'

    - name: Run Netdata installer (non-interactive)
      command: bash /tmp/netdata-install.sh --non-interactive
      args:
        creates: /usr/sbin/netdata

    - name: Ensure Netdata service is started
      service:
        name: netdata
        state: started
        enabled: yes

    - name: Ensure Netdata listens on all interfaces
      lineinfile:
        path: /etc/netdata/netdata.conf
        regexp: '^#?\s*bind to\s*='
        line: 'bind to = 0.0.0.0'
        insertafter: '^\[web\]'
      notify: restart netdata

  handlers:
    - name: restart netdata
      service:
        name: netdata
        state: restarted
