---
- hosts: backend
  become: yes

  tasks:

    - name: Install required packages
      apt:
        name:
          - curl
          - wget
        state: present
        update_cache: yes

    - name: Download Netdata installation script
      get_url:
        url: "https://my-netdata.io/kickstart.sh"
        dest: "/tmp/netdata-install.sh"
        mode: 0755

    - name: Run Netdata installer (non-interactive)
      command: "bash /tmp/netdata-install.sh --non-interactive"
      args:
        creates: /etc/netdata/netdata.conf

    - name: Ensure Netdata service is running
      service:
        name: netdata
        state: started
        enabled: yes

    - name: Update netdata.conf to listen on 0.0.0.0
      lineinfile:
        path: /etc/netdata/netdata.conf
        regexp: '^#?bind socket to IP ='
        line: 'bind socket to IP = 0.0.0.0'
      notify: restart netdata

  handlers:
    - name: restart netdata
      service:
        name: netdata
        state: restarted
